=== jeremux/BDA/tp3/exo1/exo1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	
<!-- DEFINITION DES TYPES -->
	
<!-- heure comprise entre 2h30 et 16h50 -->
	<xs:simpleType name="typeHeure">
		<xs:restriction base="xs:time">
			<xs:minInclusive value="02:30:00"/>
			<xs:maxInclusive value="16:50:00"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- nombre reel >= -3476.4 et < 5 en prÃ©cision simple -->
	<xs:simpleType name="typeReel">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="1"/>
			<xs:minInclusive value="-3476.4"/>
			<xs:maxExclusive value="5.0"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- chaine de 4 caractÃ¨res -->
	<xs:simpleType name="quatreCaracT">
		<xs:restriction base="xs:string">
			<xs:length value="4" fixed="true"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="typeImage">
		<xs:restriction base="xs:token">
			<xs:enumeration value="jpg"/>
			<xs:enumeration value="gif"/>
			<xs:enumeration value="png"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="typeIsbn">
		<xs:restriction base="xs:token">
			<xs:pattern value="[0-9]{13}"/>
		</xs:restriction>
	</xs:simpleType>
	
	
	
	<xs:element name="exo1">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="heure" type="typeHeure" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="reel" type="typeReel" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="quatreCarac" type="quatreCaracT" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="image" type="typeImage" minOccurs="1" maxOccurs="unbounded"/>
				<xs:element name="isbn" type="typeIsbn" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jeremux/BDA/tp3/exo1/exo1.xml
<?xml version="1.0" encoding="UTF-8"?>

<exo1 xsi:noNamespaceSchemaLocation="exo1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<heure> 02:30:00 </heure>
	<heure> 07:45:00</heure>
	<!--<heure>17:50:00</heure>-->

	<reel>-3333.7</reel>
	<reel>-3476.4</reel>
	<!--<reel>-3333.74</reel>-->
	<!--<reel>5</reel>-->
	<!--<reel>-3333.74</reel>-->
	
	<quatreCarac>azer</quatreCarac>
	<quatreCarac>Â²*-+</quatreCarac>
	<!--<quatreCarac></quatreCarac>-->
	<!--<quatreCarac>1</quatreCarac>-->
	
	<image>jpg</image>
	<image>png</image>
	<image>gif</image>
	<!--<image>autre</image>-->
	
	<isbn>1234567890123</isbn>
	<!--<isbn>123456789012</isbn>-->
	<!--<isbn>abcdefghijklm</isbn>-->
</exo1>
